package XOR::Markdown {

  # ABSTRACT: Markdown renderer with Perl extensions

  use strict;
  use warnings;
  use 5.020;
  use experimental qw( signatures postderef );
  use base 'Text::Markdown::PerlExtensions';
  use XOR;

=head1 SYNOPSIS

 use XOR;

 my $html = XOR->new->markdown->markdown(<<~'MD');
   Check out M<FFI::Platypus> by A<PLICEASE>.
   MD

=head1 DESCRIPTION

This is a subclass of L<Text::Markdown::PerlExtensions> that adds the
following extensions:

=over 4

=item C<< ME<lt>ModuleE<gt> >>

=item C<< ME<lt>text|ModuleE<gt> >>

=item C<< ME<lt>Module#fragmentE<gt> >>

Link to the documentation for a module.  If the module's documentation
is generated by this site, or a sister site (see L<XOR::Pods>), then
the link goes there, otherwise it goes to MetaCPAN.  An optional
C<text> may be given for the link text, otherwise the module name is
used.

=item C<< AE<lt>AUTHORE<gt> >>

=item C<< AE<lt>text|AUTHORE<gt> >>

Link to the MetaCPAN page for a CPAN author.

=item Fenced code with a language

 ```perl
 use strict;
 use warnings;
 ```

Code blocks with a language are rendered as
C<< <pre class="sh_I<lang>"> >> so that they can be highlighted by
SHJS.

=back

=head1 CONSTRUCTOR

=head2 new

 my $md = XOR::Markdown->new;

Create a new Markdown renderer.  Arguments are passed on to
L<Text::Markdown::PerlExtensions>.  The C<XOR> singleton must already
have been created before rendering any C<< ME<lt>E<gt> >> links.

=cut

  sub new ($class, @args)
  {
    my $self = $class->SUPER::new(@args);

    $self->add_formatting_code( M => sub ($stuff) {
      my $text;
      my $fragment = '';

      if($stuff =~ s/(#.*)$//)
      {
        $fragment = $1;
      }
      if($stuff =~ s/^(.*)\|//)
      {
        $text = $1;
      }

      my $name = $stuff;
      $text //= $name;

      my $href = XOR->new->pods->get_link($name) // "https://metacpan.org/pod/$name$fragment";
      return qq{<a href="$href$fragment" class="module">$text</a>};
    });

    $self->add_formatting_code( A => sub ($name) {
      my $text = $name =~ s/^(.*)\|// ? $1 : $name;
      return qq{<a href="https://metacpan.org/author/$name" class="cpan_author">$text</a>};
    });

    $self;
  }

  sub _DoCodeSpans ($self, $text)
  {
    $text =~ s@
            (?<!\\)        # Character before opening ` can't be a backslash
            (`+)        # $1 = Opening run of `
            ([a-z_0-9]+)\n
            (.+?)        # $2 = The code block
            (?<!`)
            \1            # Matching closer
            (?!`)
        @
             my $lang = "$2";
             my $c = "$3";
             $c =~ s/^[ \t]*//g; # leading whitespace
             $c =~ s/[ \t]*$//g; # trailing whitespace
             $c = $self->_EncodeCode($c);
            "<pre class=\"sh_$lang\">$c</pre>";
        @egsx;

    $text = $self->SUPER::_DoCodeSpans($text);

    $text;
  }
}

1;
