use strict;
use warnings;
use 5.020;
use experimental qw( signatures postderef );

package XOR::Pods {

  # ABSTRACT: Render POD from CPAN distributions as HTML

  use Archive::Libarchive::Peek;
  use URI;
  use URI::file;
  use Path::Tiny ();
  use JSON::MaybeXS qw( decode_json JSON );
  use Template;
  use XOR;

=head1 SYNOPSIS

 use XOR;

 my $pods = XOR->new( root => '.' )->pods;
 $pods->add_dist('https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/FFI-Platypus-2.08.tar.gz');
 $pods->add_sister_site('https://alienfile.org');
 $pods->generate_html;

=head1 DESCRIPTION

This class extracts POD from CPAN distribution tarballs and renders it
as HTML under L</fs_root>.  Links between modules (including those in
L<sister sites|/add_sister_site>) point to the generated HTML, and
other links go to MetaCPAN.

The site must provide two templates in the C<templates> directory under
L<root|XOR/root>; defaults are not provided:

=over 4

=item C<pod.html.tt>

Used for each module or script.  It is passed C<title> (the module
name), C<h1> (the module name, with links to parent modules where they
exist) and C<pod> (the rendered HTML), along with the
L<common variables|XOR/common_vars>.

=item C<dist.html.tt>

Used for the index of all distributions.  It is passed C<title> and
C<dists>, which is a list of hashes with a C<name> key for the
distribution name, and a C<pods> key with a list of hashes with C<name>
and C<href> keys, along with the L<common variables|XOR/common_vars>.

=back

=head1 CONSTRUCTOR

=head2 new

 my $pods = XOR::Pods->new;

Create a new instance.

=cut

  sub new ($class) {
    bless {}, $class;
  }

=head1 METHODS

=head2 current

 my $name = $pods->current;
 $pods->current($name);

Gets or sets the name of the module currently being rendered.

=cut

  sub current ($self, $new=undef) {
    if(defined $new) {
      $self->{current} = $new;
    }
    $self->{current};
  }

=head2 fs_root

 my $dir = $pods->fs_root;

Returns the directory that the HTML is written to as a L<Path::Tiny>
object.  This is the C<pod> directory under
L<docs_root|XOR/docs_root>.

=cut

  sub fs_root ($self) {
    $self->{fs_root} ||= XOR->new->docs_root->child('pod');
  }

=head2 url_prefix

 my $prefix = $pods->url_prefix;
 $pods->url_prefix($prefix);

Gets or sets the URL path prefix for the generated HTML.  Defaults to
C</pod/>.

=cut

  sub url_prefix ($self, $new=undef) {
    $self->{url_prefix} = $new if defined $new;
    $self->{url_prefix} ||= "/pod/"
  }

=head2 add_dist

 $pods->add_dist($location);

Adds a distribution tarball.  C<$location> can be either a path to a
local file, or a URL.  The C<.pm> and C<.pod> files in the C<lib>
directory, and the scripts in the C<bin> directory, are rendered as
HTML.  Other files in C<lib> (except for C<.xs> and C<typemap> files)
are copied as-is, so that images and the like can be referenced from
the POD.  The distribution name is taken from C<META.json>.

=cut

  sub add_dist ($self, $location) {
    $self->{at_least_one} = 1;

    my $url = -f $location ? URI::file->new(Path::Tiny->new($location)->absolute->stringify) : URI->new($location);
    say "$url";
    my $tarball = XOR->new->web->get($url);

    my $peek = Archive::Libarchive::Peek->new(
      memory => \$tarball,
    );

    my @pod_list;
    my $dist_name;

    $peek->iterate(sub ($filename, $content, $e) {
      return unless $e->filetype eq 'reg';

      # want to also handle bin directory
      if($filename =~ m{^[^/]+/lib/(.+)$})
      {
        my $path = $1;
        if($path =~ /\.(pod|pm)$/)
        {
          my $name = $path;
          $name =~ s{\.(pod|pm)$}{};
          $name =~ s{/}{::}g;

          my $href = $path;
          $href =~ s{\.(pod|pm)$}{.html};

          $self->{pod}->{$name} = {
            content => $content,
            href    => $self->url_prefix . $href,
          };
          push @pod_list, $name;
        }
        else
        {
          return if $path =~ /\.xs$/;
          return if $path =~ /\/typemap$/;
          say "data: $path";
          $self->{data}->{$path} = $content;
        }
      }
      elsif($filename =~ m{^[^/]+/bin/(.+)$})
      {
        my $name = $1;
        $self->{pod}->{$name} = {
          content => $content,
          href    => $self->url_prefix . "$name.html",
        };
        push @pod_list, $name;
      }
      elsif($filename =~  m{^[^/]+/META.json$})
      {
        my $meta = decode_json($content);
        $dist_name = $meta->{name};
      }
    });

    if($dist_name)
    {
      $self->{dist}->{$dist_name} = [ sort @pod_list ];
    }
    else
    {
      warn "unknown dist for $url";
    }
  }

=head2 add_sister_site

 $pods->add_sister_site($url);

Adds the modules documented on another site generated by XOR, so that
links to those modules point to that site.  The list of modules is
read from C</pod/index.json> on C<$url>.

=cut

  sub add_sister_site ($self, $url) {
    $url = URI->new($url) unless ref $url;
    my $index_url = $url->clone;
    $index_url->path("/pod/index.json");
    say $url;
    foreach my $dist (decode_json(XOR->new->web->get($index_url))->@*)
    {
      foreach my $pod ($dist->{pods}->@*)
      {
        my $pod_url = $url->clone;
        $pod_url->path($pod->{href});
        $self->{sister_pod}->{$pod->{name}}->{href} = $pod_url->as_string;
      }
    }
  }

=head2 generate_html

 $pods->generate_html;

Writes the HTML for each module and script, any data files, and the
distribution index (C<index.html> and C<index.json>) to L</fs_root>.
Does nothing unless at least one distribution was added with
L</add_dist>.

=cut

  sub generate_html ($self) {

    return unless $self->{at_least_one};

    # write out each pod file as .html
    foreach my $name (sort keys $self->{pod}->%*)
    {
      my $p = XOR::Pods::HTML->new;
      my $html;
      $p->output_string(\$html);
      $p->index(1);
      $p->html_header_before_title('<!--');
      $p->html_header_after_title('-->');
      $p->html_footer('');
      $p->pods($self);
      $p->{Tagmap}->{'Verbatim'} = "\n<pre class=\"sh_perl\">";
      $p->{Tagmap}->{'VerbatimFormatted'} = "\n<pre class=\"sh_perl\">";
      $self->current($name);

      $p->parse_string_document($self->{pod}->{$name}->{content});

      my $path = $self->fs_root->child(do {
        my @parts = split /::/, $name;
        $parts[-1] .= '.html';
        @parts;
      });

      $path->parent->mkpath;

      my $h1;
      if($name =~ /::/)
      {
        my @parts = split /::/, $name;
        my $last = pop @parts;
        my $sofar;
        foreach my $part (@parts)
        {
          if(defined $sofar)
          {
            $sofar .= "::$part";
            $h1 .= "::";
          }
          else
          {
            $sofar = $part;
          }
          my $href = $self->get_link($sofar);
          if(defined $href)
          {
            $h1 .= "<a href=\"$href\">$part</a>";
          }
          else
          {
            $h1 .= $part;
          }
        }
        $h1 .= "::$last";
      }
      else
      {
        $h1 = $name;
      }

      my $full_html;
      my $xor = XOR->new;
      $xor->tt->process('pod.html.tt', {
        title => $name,
        h1    => $h1,
        pod   => $html,
        $xor->common_vars,
      }, \$full_html);

      $path->spew_utf8($full_html);
    }

    # write out data files, images, etc.
    foreach my $path (sort keys $self->{data}->%*) {
      my $content = $self->{data}->{$path};
      $path = $self->fs_root->child($path);
      $path->parent->mkpath;
      $path->spew_raw($content);
    }

    # generate the dist index
    {
      my @dists;

      foreach my $dist_name (sort keys $self->{dist}->%*)
      {
        push @dists, { name => $dist_name, pods => [ map { { href => $self->get_link($_), name => $_ } } $self->{dist}->{$dist_name}->@* ] };
      }

      my $html;
      my $xor = XOR->new;
      $xor->tt->process('dist.html.tt', {
        title => 'Documentation',
        dists => \@dists,
        $xor->common_vars,
      }, \$html);

      $self->fs_root->child('index.html')->spew_utf8($html);
      $self->fs_root->child('index.json')->spew_raw(JSON()->new->canonical->pretty->encode(\@dists));
    }
  }

=head2 get_link

 my $href = $pods->get_link($name);

Returns the URL of the documentation for module C<$name>, if it is
documented on this site or a sister site, otherwise C<undef>.

=cut

  sub get_link ($self, $name) {
    $self->{pod}->{$name}->{href} // $self->{sister_pod}->{$name}->{href};
  }

}

package XOR::Pods::HTML {

  use parent qw( Pod::Simple::HTML );

  sub pods ($self, $new=undef) {
    if($new) {
      $self->{pods} = $new;
    }
    $self->{pods};
  }

  sub do_pod_link ($self, $link)
  {
    if($link->tagname eq 'L' && $link->attr('type') eq 'pod') {
      my $to      = $link->attr('to');
      my $section = $link->attr('section');
      if(defined $to)
      {
        if(my $path = $self->pods->get_link($to)) {
          $path .= "#" . $self->section_escape($section) if defined $section;
          return $path;
        }
      }
      else
      {
        if(defined $section) {
          return "#" . $self->section_escape($section);
        }
      }
    }
    return $self->SUPER::do_pod_link($link);
  }

}

1;
